# 指定服务端口
server:
  port: 8081
# 指定服务名
spring:
  application:
    name: CLIENT01
# 指定服务注册中心地址
eureka:
  client:
    service_url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
  instance:
    lease-expiration-duration-in-seconds: 10 # 服务器接收最大时间
    lease-renewal-interval-in-seconds: 5 # 客户端发送时间