server:
  port: 8082
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  application:
    name: MessageReceiver
  cloud:
    function:
      definition: msg
    stream:
      binders:
        MS:
          type: rabbit
      bindings:
        input:
          destination: rabbit
          default-binder: MS
          group: message
          consumer:
            concurrency: 1
#      bindings:
        msg-in-0:
          destination: testExchange
#          content-type: application/json
          group: test_new
