server:
  port: 8761 # Eureka Server 默认端口号

# 必备(不能有下划线 不区分大小写)
spring:
  application:
    name: EUREKASERVER # 指定服务名称 (唯一标识)

# 暴露服务地址
eureka:
  client:
    service-url: # Eureka Server 服务注册中心的地址
      defaultZone: http://localhost:8762/eureka,http://localhost:8763/eureka # 8761
#       defaultZone: http://localhost:8761/eureka,http://localhost:8763/eureka # 8762
#       defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka # 8763
#     fetch-registry: false # 关闭立即注册
#     register-with-eureka: false # 让服务注册中心不为客户端
